name: basics
description: From the Udemy course "The complete Dart Language Guide".
version: 1.0.0

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
